### ISSUE TITLE
By canceling the payment, the invoice is created automatically

### ISSUE THREAD

**Issue by matts93** [bagisto-europe/multisafepay#19]
By selecting a payment type such as Mastercard or Apple Pay, once the order is completed and redirected to the payment link, click on cancel, the invoice is generated, which remains pending but there is no way to record the payment

**Comment by ghermans** [comment]
Hi @matts93 , while we are checking the issue you reported, i would like to ask if you enabled SecondChance on your account ?

![image](https://github.com/bagisto-europe/multisafepay/assets/1594411/d331d7fe-a069-4f4f-823b-0e69089fa593)

**Comment by matts93** [comment]
yes, is enable

**Comment by ghermans** [comment]
The issue has been resolved and is available by running the following command 
```
composer require bagisto-eu/multisafepay:dev-main
```
