### ISSUE TITLE
error after install 

### ISSUE THREAD

**Issue by 10twenty** [bagisto-europe/multisafepay#31]
[proxy_fcgi:error [pid 8440:tid 9458 [client XXX.XXX.XXX.XXX:0 AH01071: Got error 'PHP message: PHP Fatal error: Declaration of Bagisto\\MultiSafePay\\Core::getConfigData($field, $channel = null, $locale = null) m............udwaysapps.com/dfvqfvawrg/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(297): Illuminate\\Foundation\\Application->resolve()\n#4 /home/1373426.cloudwaysapps.com/dfvqfvawrg/public_html/vendor/laravel/framework/src/Ill...'
--
 

<br class="Apple-interchange-newline">

**Comment by ghermans** [comment]
@10twenty thank you for reporting this issue. To help us investigate further, could you please provide the version number of Bagisto you are using?

**Comment by 10twenty** [comment]
v2.2.2 
Thank you

**Comment by ghermans** [comment]
@10twenty have you experienced any problems with the new version?
